version: '3'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - backend-network
    ports:
      - 80:80

  app1:
    build: ./apps/app1
    networks:
      - backend-network
  app2:
    build: ./apps/app2
    networks:
      - backend-network

networks:
  backend-network: