version: '3'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - backend-network
    ports:
      - 80:80

  nodejs:
    build: ./
    networks:
      - backend-network

networks:
  backend-network: